### ISSUE TITLE
Small error in regex

### ISSUE THREAD

**Issue by nathanvoller** [sirLisko/uk-postcode-validator#1]
Noticed a slight error in your regex.

In the third group you've got `[AZa-z]`, which I think should be `[A-Za-z]`

**Comment by sirLisko** [comment]
Hey @nathanvoller,

Thanks for submitting this and good catch :)
Just noticed that copy&pasting the RegEx from this [gov.uk document](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/488478/Bulk_Data_Transfer_-_additional_validation_valid_from_12_November_2015.pdf) introduced the error.

Fixed in #2.

**Comment by sirLisko** [comment]
New version published on npm https://www.npmjs.com/package/uk-postcode-validator/v/1.0.2.

Thanks again 🙇
